# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41cf16c3cec12ec48544e7e5a920b0b59a7daa0bc5ca5be5aba7049411d2bf6c10c30e26ff9c7cc2f4820b83bb20377c9b6bb244f39fdfc8f77eb822f524b28f

test:
  secret_key_base: ccf4cec8bbcb00b331a4f856ce5df56b7a136e5607d757c87a07d224b6c64bc4c46eef10a95d786ab49c53010f618c9b315d77aa5837c443d853d2aadbe8bbbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
